In [1]:
ticker = "HOOD"

## Assume we run the update
#### Retrieve the previously Impaction metrics

In [2]:
# Reimport to refresh the latest version
import importlib
import sys

# Remove cached modules
if 'Quant_Impact_DB_Agent' in sys.modules:
    del sys.modules['Quant_Impact_DB_Agent']
if 'Quant_Impact_Storage_Agent' in sys.modules:
    del sys.modules['Quant_Impact_Storage_Agent']
if 'Quant_Impact_Update_Metrics' in sys.modules:
    del sys.modules['Quant_Impact_Update_Metrics']

# Fresh import
from Quant_Impact_DB_Agent import QuantImpactDBAgent
from shared_clients import shared_clients

# Initialize
await shared_clients.initialize()
db_agent = QuantImpactDBAgent(shared_clients=shared_clients)

ticker = ticker

# Smart logic: Check if exists, then retrieve OR generate
if db_agent.check_data_exists(ticker):
    print(f"✅ Data exists for {ticker}, retrieving from Redis...")
    result = db_agent.retrieve_datasets(ticker)
    
    # Show metadata with previous update time
    if 'meta_info' in result:
        meta = result['meta_info']
        print(f"\n📋 Existing Data Metadata:")
        print(f"   Last Updated: {meta.get('retrieved_date', 'N/A')}")
        print(f"   Macro Factors: {meta.get('macro_factors', 'N/A')}")
        print(f"   Micro Factors: {meta.get('micro_factors', 'N/A')}")
else:
    print(f"⚠️ No data found for {ticker}, generating fresh...")
    result = await db_agent.generate_and_store(ticker)

# Debug: Check what keys are available
print(f"🔍 Available keys in result: {list(result.keys())}")

# Safely extract data with fallbacks
risk_share_index = result.get('risk_share_index', {})
macro_volatility_df = result.get('macro_volatility_df')
micro_volatility_df = result.get('micro_volatility_df')
impact_metrics_df = result.get('impact_metrics_df')
macro_total_impact_df = result.get('macro_total_impact_df')
micro_total_impact_df = result.get('micro_total_impact_df')
Factor_Risk_Reward = result.get('Factor_Risk_Reward')
factor_time_df = result.get('factor_time_df')

# Show update time
if 'meta_info' in result:
    print(f"\n📅 Data Last Updated: {result['meta_info']['retrieved_date']}")
else:
    print("\n⚠️ No meta_info found in result")

factor_time_df = result.get('factor_time_df')

/Users/xikinki/Desktop/QandQ_AI/Fintegrate_AI_File/New_Fintegrate_AI(V3)/Quant_Impact_Agent/Quant_Impact_DB_Agent.py:37: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet. 	from pydantic.v1 import BaseModel

  from Quant_Impact_Agent.Quant_Impact_Storage_Agent import QuantImpactStorageAgent

🚀 Initializing shared client pool...
🤖 Initializing LLM clients...
🗄️ Initializing Redis pools...
🌐 Initializing HTTP session...
🧪 Testing connections...
✅ All Redis connections verified
⏱️ Initialization time: 0.73 seconds
⚠️ No data found for HOOD, generating fresh...
======================================================================
🚀 QUANT IMPACT DB AGENT - GENERATE & STORE
======================================================================
📊 Ticker: HOOD
🌐 Language: English (Default)
⏰ Start: 2025-10-08 00:46:52
======================================================================

🔄 Running Storage Agent pipeline...
🚀 Starting Quant Impact Analysis for HOOD

🔥 Warming up Market Expectation and Sector Analyst for HOOD...
🧠 Starting SMART Data Pool retrieval for HOOD...
============================================================
✅ Added Market_Expectation_Agent to warm-up list
✅ Added Sector_Analyst_Agent to warm-up list
🔍 Checking 2 specified agents for update status...

📊 Update Status Summary:
========================================
market_expectation: 🔄 UPDATE NEEDED
   Reason: No data found for ticker HOOD
sector_analysis: 🔄 UPDATE NEEDED
   Reason: No data found for HOOD

🚀 Updating 2 agents that need fresh data...

🚀 Executing 2 SMART updates concurrently...
📈 [SMART] Updating Market Expectation for HOOD...
🏭 [SMART] Updating Sector Analysis for HOOD...
🔍 Loading sector index CSV from: /Users/xikinki/Desktop/QandQ_AI/Fintegrate_AI_File/New_Fintegrate_AI(V3)/Sector_Analyst_Agent/sector_index_tickers.csv
✅ CSV file exists, loading...
   Loaded 93 rows, columns: ['Ticker', 'Description']
✅ Loaded 93 sector indices from CSV
   Sample tickers: ['^GSPC', '^DJI', '^IXIC', 'SPY', 'QQQ']
🎯 Starting analysis for ticker: HOOD
🆕 Performing fresh analysis...
🔄 Trying 365 days period: 2024-10-08 to 2025-10-09
✅ Found data for 365 days period (250 data points)
📊 Using analysis period: 2024-10-08 to 2025-10-09
📈 Data points: 250
1️⃣ Analyzing price trends with enhanced segmentation...
✅ Found 32 trend segments
2️⃣ Processing trend segments...
3️⃣ Fetching news data with multiprocessing...
🚀 Starting multiprocessing news fetch for 32 trends
📊 Using 10 processes

/Users/xikinki/Desktop/QandQ_AI/Fintegrate_AI_File/New_Fintegrate_AI(V3)/Market_Expectation_Agent/Stock_Trend_Storage_Agent.py:433: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, start=start_date, end=end_date, progress=False)

🔄 Process 1: Processing downtrend1
🔄 Process 10: Processing downtrend5
🔄 Process 7: Processing downtrend4
🔄 Process 5: Processing downtrend3
🔄 Process 8: Processing uptrend4
🔄 Process 3: Processing downtrend2
🔄 Process 9: Processing uptrend5
🔄 Process 6: Processing uptrend3
🔄 Process 4: Processing uptrend2
🔄 Process 2: Processing uptrend1
✅ Process 7: Completed downtrend4 with 6 news articles
🔄 Process 11: Processing uptrend6
✅ Process 1: Completed downtrend1 with 6 news articles
🔄 Process 12: Processing uptrend7
✅ Process 5: Completed downtrend3 with 6 news articles
🔄 Process 13: Processing downtrend6
✅ Process 6: Completed uptrend3 with 9 news articles
🔄 Process 14: Processing downtrend7
✅ Process 2: Completed uptrend1 with 8 news articles
🔄 Process 15: Processing uptrend8
✅ Process 9: Completed uptrend5 with 9 news articles
🔄 Process 16: Processing downtrend8
✅ Process 8: Completed uptrend4 with 22 news articles
🔄 Process 17: Processing uptrend9
✅ Process 10: Completed downtrend5 with 15 news articles
🔄 Process 18: Processing downtrend9
✅ Process 17: Completed uptrend9 with 11 news articles
🔄 Process 19: Processing uptrend10
✅ Process 13: Completed downtrend6 with 21 news articles
🔄 Process 20: Processing downtrend10
✅ Process 3: Completed downtrend2 with 33 news articles
🔄 Process 21: Processing uptrend11
✅ Process 11: Completed uptrend6 with 27 news articles
🔄 Process 22: Processing uptrend12
✅ Process 12: Completed uptrend7 with 31 news articles
🔄 Process 23: Processing downtrend11
✅ Process 16: Completed downtrend8 with 30 news articles
🔄 Process 24: Processing downtrend12
✅ Process 14: Completed downtrend7 with 28 news articles
🔄 Process 25: Processing uptrend13
✅ Process 15: Completed uptrend8 with 31 news articles
🔄 Process 26: Processing uptrend14
✅ Process 18: Completed downtrend9 with 13 news articles
🔄 Process 27: Processing downtrend13
✅ Process 19: Completed uptrend10 with 11 news articles
🔄 Process 28: Processing uptrend15
✅ Process 24: Completed downtrend12 with 12 news articles
🔄 Process 29: Processing downtrend14
✅ Process 20: Completed downtrend10 with 11 news articles
🔄 Process 30: Processing uptrend16
✅ Process 25: Completed uptrend13 with 15 news articles
🔄 Process 31: Processing uptrend17
✅ Process 28: Completed uptrend15 with 11 news articles
🔄 Process 32: Processing downtrend15
✅ Process 22: Completed uptrend12 with 25 news articles
✅ Process 29: Completed downtrend14 with 12 news articles
✅ Process 26: Completed uptrend14 with 20 news articles
✅ Process 23: Completed downtrend11 with 23 news articles
✅ Process 4: Completed uptrend2 with 64 news articles
✅ Process 32: Completed downtrend15 with 13 news articles
✅ Process 30: Completed uptrend16 with 23 news articles
✅ Process 31: Completed uptrend17 with 19 news articles
✅ Process 27: Completed downtrend13 with 25 news articles
✅ Process 21: Completed uptrend11 with 123 news articles
✅ Multiprocessing completed: 32 trends processed
4️⃣ Analyzing news with DeepSeek using multiprocessing...
🧠 Starting multiprocessing DeepSeek analysis for HOOD
📊 Total trends to process: 32
📊 Using 10 processes
============================================================
🧠 Process 1: Processing LLM batch ['downtrend1', 'uptrend1', 'downtrend2']
📡 Process 1: Calling LLM API for batch ['downtrend1', 'uptrend1', 'downtrend2']...
🧠 Process 2: Processing LLM batch ['uptrend2', 'downtrend3', 'uptrend3']
📡 Process 2: Calling LLM API for batch ['uptrend2', 'downtrend3', 'uptrend3']...
🧠 Process 3: Processing LLM batch ['downtrend4', 'uptrend4', 'uptrend5']
📡 Process 3: Calling LLM API for batch ['downtrend4', 'uptrend4', 'uptrend5']...
🧠 Process 4: Processing LLM batch ['downtrend5', 'uptrend6', 'uptrend7']
📡 Process 4: Calling LLM API for batch ['downtrend5', 'uptrend6', 'uptrend7']...
🧠 Process 5: Processing LLM batch ['downtrend6', 'downtrend7', 'uptrend8']
📡 Process 5: Calling LLM API for batch ['downtrend6', 'downtrend7', 'uptrend8']...
🧠 Process 6: Processing LLM batch ['downtrend8', 'uptrend9', 'downtrend9']
📡 Process 6: Calling LLM API for batch ['downtrend8', 'uptrend9', 'downtrend9']...
🧠 Process 7: Processing LLM batch ['uptrend10', 'downtrend10', 'uptrend11']
📡 Process 7: Calling LLM API for batch ['uptrend10', 'downtrend10', 'uptrend11']...
🧠 Process 8: Processing LLM batch ['uptrend12', 'downtrend11', 'downtrend12']
📡 Process 8: Calling LLM API for batch ['uptrend12', 'downtrend11', 'downtrend12']...
🧠 Process 9: Processing LLM batch ['uptrend13', 'uptrend14', 'downtrend13']
📡 Process 9: Calling LLM API for batch ['uptrend13', 'uptrend14', 'downtrend13']...
🧠 Process 10: Processing LLM batch ['uptrend15', 'downtrend14', 'uptrend16']
📡 Process 10: Calling LLM API for batch ['uptrend15', 'downtrend14', 'uptrend16']...
🧠 Process 11: Processing LLM batch ['uptrend17', 'downtrend15']
📡 Process 11: Calling LLM API for batch ['uptrend17', 'downtrend15']...
🔍 Matching sector index for Robinhood Markets, Inc.
   Available sector indices: 93 entries
   Checking LLM client availability...
   Initializing LLM client...
   Getting LLM call agent...
   Getting structured LLM...
   Calling LLM for sector matching...
✅ Process 1: DeepSeek API call successful
📝 Raw response length: 573 characters
📝 Raw response preview: {
  "downtrend1": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Revenue missed expectations and promotions impacted performance [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
  "uptr...
🔍 Raw LLM response (first 500 chars): {
  "downtrend1": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Revenue missed expectations and promotions impacted performance [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
  "uptrend1": {
    "macro_reason": "",
    "micro_reason": "• (Product Development): New trading tools and features launched for sophisticated investors [DELIVERY] [N/A]"
  },
  "downtrend2": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Revenue missed estimates and promotions led
🧹 Cleaned response (first 500 chars): {
  "downtrend1": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Revenue missed expectations and promotions impacted performance [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
  "uptrend1": {
    "macro_reason": "",
    "micro_reason": "• (Product Development): New trading tools and features launched for sophisticated investors [DELIVERY] [N/A]"
  },
  "downtrend2": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Revenue missed estimates and promotions led
✅ JSON parsing strategy 1 succeeded
✅ Process 1: Found analysis for downtrend1
✅ Process 1: Found analysis for uptrend1
✅ Process 1: Found analysis for downtrend2
✅ Process 1: Batch complete: 3 trends processed
✅ Process 10: DeepSeek API call successful
📝 Raw response length: 392 characters
📝 Raw response preview: {
  "uptrend15": {
    "macro_reason": "",
    "micro_reason": "• (Business Line): Added to S&P 500 index [DELIVERY] [N/A]"
  },
  "downtrend14": {
    "macro_reason": "• (Monetary Policy): Fed cut ra...
🔍 Raw LLM response (first 500 chars): {
  "uptrend15": {
    "macro_reason": "",
    "micro_reason": "• (Business Line): Added to S&P 500 index [DELIVERY] [N/A]"
  },
  "downtrend14": {
    "macro_reason": "• (Monetary Policy): Fed cut rates by 25bps [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend16": {
    "macro_reason": "• (Monetary Policy): Fed rate cuts implemented [DELIVERY] [N/A]",
    "micro_reason": ""
  }
}
🧹 Cleaned response (first 500 chars): {
  "uptrend15": {
    "macro_reason": "",
    "micro_reason": "• (Business Line): Added to S&P 500 index [DELIVERY] [N/A]"
  },
  "downtrend14": {
    "macro_reason": "• (Monetary Policy): Fed cut rates by 25bps [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend16": {
    "macro_reason": "• (Monetary Policy): Fed rate cuts implemented [DELIVERY] [N/A]",
    "micro_reason": ""
  }
}
✅ JSON parsing strategy 1 succeeded
✅ Process 10: Found analysis for uptrend15
✅ Process 10: Found analysis for downtrend14
✅ Process 10: Found analysis for uptrend16
✅ Process 10: Batch complete: 3 trends processed
✅ Process 6: DeepSeek API call successful
📝 Raw response length: 492 characters
📝 Raw response preview: {
  "downtrend8": {
    "macro_reason": "• (Trade Policy): Trump implemented 25% auto tariffs and 10% tariffs on Australian goods [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend9": {
    "ma...
🔍 Raw LLM response (first 500 chars): {
  "downtrend8": {
    "macro_reason": "• (Trade Policy): Trump implemented 25% auto tariffs and 10% tariffs on Australian goods [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend9": {
    "macro_reason": "• (Trade Policy): Tech tariff reprieve announced [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "downtrend9": {
    "macro_reason": "• (Monetary Policy): Fed Chair Powell maintaining tight monetary policy amid inflation concerns [DELIVERY] [N/A]",
    "micro_reason": ""
  }
}
🧹 Cleaned response (first 500 chars): {
  "downtrend8": {
    "macro_reason": "• (Trade Policy): Trump implemented 25% auto tariffs and 10% tariffs on Australian goods [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend9": {
    "macro_reason": "• (Trade Policy): Tech tariff reprieve announced [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "downtrend9": {
    "macro_reason": "• (Monetary Policy): Fed Chair Powell maintaining tight monetary policy amid inflation concerns [DELIVERY] [N/A]",
    "micro_reason": ""
  }
}
✅ JSON parsing strategy 1 succeeded
✅ Process 6: Found analysis for downtrend8
✅ Process 6: Found analysis for uptrend9
✅ Process 6: Found analysis for downtrend9
✅ Process 6: Batch complete: 3 trends processed
✅ Process 3: DeepSeek API call successful
📝 Raw response length: 502 characters
📝 Raw response preview: {
  "downtrend4": {
    "macro_reason": "• (Monetary Policy): Fed cut interest rates by 25 basis points [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend4": {
    "macro_reason": "",
    "micr...
🔍 Raw LLM response (first 500 chars): {
  "downtrend4": {
    "macro_reason": "• (Monetary Policy): Fed cut interest rates by 25 basis points [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend4": {
    "macro_reason": "",
    "micro_reason": "• (Business Outlook): Company expanded offerings and customer base with elevated trading volumes [DELIVERY] [BETTER_THAN_EXPECTATION]"
  },
  "uptrend5": {
    "macro_reason": "",
    "micro_reason": "• (Leadership): CEO announced aggressive plans for 2025 expansion [DELIVERY] [N/A]"
  }
🧹 Cleaned response (first 500 chars): {
  "downtrend4": {
    "macro_reason": "• (Monetary Policy): Fed cut interest rates by 25 basis points [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend4": {
    "macro_reason": "",
    "micro_reason": "• (Business Outlook): Company expanded offerings and customer base with elevated trading volumes [DELIVERY] [BETTER_THAN_EXPECTATION]"
  },
  "uptrend5": {
    "macro_reason": "",
    "micro_reason": "• (Leadership): CEO announced aggressive plans for 2025 expansion [DELIVERY] [N/A]"
  }
✅ JSON parsing strategy 1 succeeded
✅ Process 3: Found analysis for downtrend4
✅ Process 3: Found analysis for uptrend4
✅ Process 3: Found analysis for uptrend5
✅ Process 3: Batch complete: 3 trends processed
✅ Process 4: DeepSeek API call successful
📝 Raw response length: 536 characters
📝 Raw response preview: {
  "downtrend5": {
    "macro_reason": "",
    "micro_reason": "• (Regulatory Action): SEC imposed $45 million settlement for securities law violations [DELIVERY] [N/A]"
  },
  "uptrend6": {
    "mac...
🔍 Raw LLM response (first 500 chars): {
  "downtrend5": {
    "macro_reason": "",
    "micro_reason": "• (Regulatory Action): SEC imposed $45 million settlement for securities law violations [DELIVERY] [N/A]"
  },
  "uptrend6": {
    "macro_reason": "",
    "micro_reason": "• (Business Partnerships): CME Group futures products launched on Robinhood platform [DELIVERY] [N/A]"
  },
  "uptrend7": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Q4 earnings beat expectations with strong profitability metrics [DELIVE
🧹 Cleaned response (first 500 chars): {
  "downtrend5": {
    "macro_reason": "",
    "micro_reason": "• (Regulatory Action): SEC imposed $45 million settlement for securities law violations [DELIVERY] [N/A]"
  },
  "uptrend6": {
    "macro_reason": "",
    "micro_reason": "• (Business Partnerships): CME Group futures products launched on Robinhood platform [DELIVERY] [N/A]"
  },
  "uptrend7": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Q4 earnings beat expectations with strong profitability metrics [DELIVE
✅ JSON parsing strategy 1 succeeded
✅ Process 4: Found analysis for downtrend5
✅ Process 4: Found analysis for uptrend6
✅ Process 4: Found analysis for uptrend7
✅ Process 4: Batch complete: 3 trends processed
✅ Process 9: DeepSeek API call successful
📝 Raw response length: 500 characters
📝 Raw response preview: {
  "uptrend13": {
    "macro_reason": "• (Trade Policy): Trump implemented 100% semiconductor tariffs [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend14": {
    "macro_reason": "",
    "micr...
🔍 Raw LLM response (first 500 chars): {
  "uptrend13": {
    "macro_reason": "• (Trade Policy): Trump implemented 100% semiconductor tariffs [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend14": {
    "macro_reason": "",
    "micro_reason": "• (Business Outlook): Bitcoin rally and crypto growth driving earnings optimism [DELIVERY] [BETTER_THAN_EXPECTATION]"
  },
  "downtrend13": {
    "macro_reason": "• (Monetary Policy): Fed signaled potential rate cut but provided no timeline [DELIVERY] [N/A]",
    "micro_reason": ""
  }
}
🧹 Cleaned response (first 500 chars): {
  "uptrend13": {
    "macro_reason": "• (Trade Policy): Trump implemented 100% semiconductor tariffs [DELIVERY] [N/A]",
    "micro_reason": ""
  },
  "uptrend14": {
    "macro_reason": "",
    "micro_reason": "• (Business Outlook): Bitcoin rally and crypto growth driving earnings optimism [DELIVERY] [BETTER_THAN_EXPECTATION]"
  },
  "downtrend13": {
    "macro_reason": "• (Monetary Policy): Fed signaled potential rate cut but provided no timeline [DELIVERY] [N/A]",
    "micro_reason": ""
  }
}
✅ JSON parsing strategy 1 succeeded
✅ Process 9: Found analysis for uptrend13
✅ Process 9: Found analysis for uptrend14
✅ Process 9: Found analysis for downtrend13
✅ Process 9: Batch complete: 3 trends processed
✅ Process 8: DeepSeek API call successful
📝 Raw response length: 532 characters
📝 Raw response preview: {
  "uptrend12": {
    "macro_reason": "",
    "micro_reason": "• (Business Partnerships): WonderFi acquisition approved by shareholders and court [DELIVERY] [N/A]"
  },
  "downtrend11": {
    "macro_...
🔍 Raw LLM response (first 500 chars): {
  "uptrend12": {
    "macro_reason": "",
    "micro_reason": "• (Business Partnerships): WonderFi acquisition approved by shareholders and court [DELIVERY] [N/A]"
  },
  "downtrend11": {
    "macro_reason": "",
    "micro_reason": "• (Business Outlook): S&P 500 inclusion snubbed despite expectations [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
  "downtrend12": {
    "macro_reason": "• (Trade Policy): Trump announced 35% tariffs on Canada and increased tariffs on dozens of countries [DELIVERY] [N/A
🧹 Cleaned response (first 500 chars): {
  "uptrend12": {
    "macro_reason": "",
    "micro_reason": "• (Business Partnerships): WonderFi acquisition approved by shareholders and court [DELIVERY] [N/A]"
  },
  "downtrend11": {
    "macro_reason": "",
    "micro_reason": "• (Business Outlook): S&P 500 inclusion snubbed despite expectations [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
  "downtrend12": {
    "macro_reason": "• (Trade Policy): Trump announced 35% tariffs on Canada and increased tariffs on dozens of countries [DELIVERY] [N/A
✅ JSON parsing strategy 1 succeeded
✅ Process 8: Found analysis for uptrend12
✅ Process 8: Found analysis for downtrend11
✅ Process 8: Found analysis for downtrend12
✅ Process 8: Batch complete: 3 trends processed
✅ Process 2: DeepSeek API call successful
📝 Raw response length: 574 characters
📝 Raw response preview: ```json
{
  "uptrend2": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Q3 earnings missed revenue estimates ($637M vs $663.5M expected) [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
...
🔍 Raw LLM response (first 500 chars): ```json
{
  "uptrend2": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Q3 earnings missed revenue estimates ($637M vs $663.5M expected) [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
  "downtrend3": {
    "macro_reason": "",
    "micro_reason": "• (Business Outlook): Technical indicators suggest near-term correction of 5-10% likely [DELIVERY] [N/A]"
  },
  "uptrend3": {
    "macro_reason": "",
    "micro_reason": "• (Business Expansion): Company expanded into crypto trading and
🧹 Cleaned response (first 500 chars): {
  "uptrend2": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Q3 earnings missed revenue estimates ($637M vs $663.5M expected) [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
  "downtrend3": {
    "macro_reason": "",
    "micro_reason": "• (Business Outlook): Technical indicators suggest near-term correction of 5-10% likely [DELIVERY] [N/A]"
  },
  "uptrend3": {
    "macro_reason": "",
    "micro_reason": "• (Business Expansion): Company expanded into crypto trading and launched
✅ JSON parsing strategy 1 succeeded
✅ Process 2: Found analysis for uptrend2
✅ Process 2: Found analysis for downtrend3
✅ Process 2: Found analysis for uptrend3
✅ Process 2: Batch complete: 3 trends processed
✅ Process 7: DeepSeek API call successful
📝 Raw response length: 575 characters
📝 Raw response preview: ```json
{
  "uptrend10": {
    "macro_reason": "",
    "micro_reason": "• (Business Partnerships): Acquired Canadian crypto firm WonderFi for $178.56 million [DELIVERY] [N/A]"
  },
  "downtrend10": {
...
🔍 Raw LLM response (first 500 chars): ```json
{
  "uptrend10": {
    "macro_reason": "",
    "micro_reason": "• (Business Partnerships): Acquired Canadian crypto firm WonderFi for $178.56 million [DELIVERY] [N/A]"
  },
  "downtrend10": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Q1 2025 earnings showed adjusted EBITDA fell short of analyst expectations [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
  "uptrend11": {
    "macro_reason": "",
    "micro_reason": "• (Product Development): Launched tokenized stock offe
🧹 Cleaned response (first 500 chars): {
  "uptrend10": {
    "macro_reason": "",
    "micro_reason": "• (Business Partnerships): Acquired Canadian crypto firm WonderFi for $178.56 million [DELIVERY] [N/A]"
  },
  "downtrend10": {
    "macro_reason": "",
    "micro_reason": "• (Financial Metrics): Q1 2025 earnings showed adjusted EBITDA fell short of analyst expectations [DELIVERY] [LESS_THAN_EXPECTATION]"
  },
  "uptrend11": {
    "macro_reason": "",
    "micro_reason": "• (Product Development): Launched tokenized stock offerings fo
✅ JSON parsing strategy 1 succeeded
✅ Process 7: Found analysis for uptrend10
✅ Process 7: Found analysis for downtrend10
✅ Process 7: Found analysis for uptrend11
✅ Process 7: Batch complete: 3 trends processed
✅ Process 5: DeepSeek API call successful
📝 Raw response length: 567 characters
📝 Raw response preview: ```json
{
    "downtrend6": {
        "macro_reason": "",
        "micro_reason": "• (Business Partnerships): CQG partnership announced for futures order routing infrastructure [DELIVERY] [N/A]"
    }...
🔍 Raw LLM response (first 500 chars): ```json
{
    "downtrend6": {
        "macro_reason": "",
        "micro_reason": "• (Business Partnerships): CQG partnership announced for futures order routing infrastructure [DELIVERY] [N/A]"
    },
    "downtrend7": {
        "macro_reason": "• (Trade Policy): Trump confirmed 25% tariffs on Mexico and Canada implemented [DELIVERY] [N/A]",

In [3]:
factor_time_df

,factor_name,scope,start_date,end_date,time_interval,duration_days
0,Fed Rate Cut Implementation,macro,2024-12-16,2024-12-19,2024-12-16 to 2024-12-19,3
1,Fed Rate Cut Implementation,macro,2025-09-09,2025-09-15,2025-09-09 to 2025-09-15,6
2,Fed Rate Cut Implementation,macro,2025-09-15,2025-09-26,2025-09-15 to 2025-09-26,11
3,Fed Rate Cut Signal No Timeline,macro,2025-08-18,2025-09-03,2025-08-18 to 2025-09-03,16
4,Fed Maintained Tight Monetary Policy,macro,2025-04-14,2025-04-21,2025-04-14 to 2025-04-21,7
5,Fed Held Rates Steady,macro,2025-03-10,2025-03-24,2025-03-10 to 2025-03-24,14
6,Trump 35% Tariffs Canada Multiple Countries,macro,2025-07-28,2025-08-01,2025-07-28 to 2025-08-01,4
7,Trump 25% Auto Tariffs Australia Goods,macro,2025-03-24,2025-04-08,2025-03-24 to 2025-04-08,15
8,Trump 25% Tariffs Mexico Canada Implemented,macro,2025-02-25,2025-03-10,2025-02-25 to 2025-03-10,13
9,Trump 100% Semiconductor Tariffs,macro,2025-08-01,2025-08-08,2025-08-01 to 2025-08-08,7
10,Tech Tariff Reprieve Announced,macro,2025-04-08,2025-04-14,2025-04-08 to 2025-04-14,6
11,Fed Rate Cut 25bps,macro,2024-12-16,2024-12-19,2024-12-16 to 2024-12-19,3
12,Fed Rate Cut 25bps,macro,2025-09-09,2025-09-15,2025-09-09 to 2025-09-15,6
13,Fed Rate Cut 25 Basis Points,macro,2024-12-16,2024-12-19,2024-12-16 to 2024-12-19,3
14,Fed Rate Cut 25 Basis Points,macro,2025-09-09,2025-09-15,2025-09-09 to 2025-09-15,6
15,Trade Policy Uncertainty Multiple Tariffs,macro,2025-02-25,2025-03-10,2025-02-25 to 2025-03-10,13
16,Trade Policy Uncertainty Multiple Tariffs,macro,2025-03-24,2025-04-08,2025-03-24 to 2025-04-08,15
17,Trade Policy Uncertainty Multiple Tariffs,macro,2025-07-28,2025-08-01,2025-07-28 to 2025-08-01,4
18,Monetary Policy Tightening Concerns,macro,2025-04-14,2025-04-21,2025-04-14 to 2025-04-21,7
19,Fed Rate Cut Expectations Unmet,macro,2025-08-18,2025-09-03,2025-08-18 to 2025-09-03,16
20,Global Trade Tensions Escalation,macro,2025-02-25,2025-03-10,2025-02-25 to 2025-03-10,13
21,Global Trade Tensions Escalation,macro,2025-03-24,2025-04-08,2025-03-24 to 2025-04-08,15
22,Global Trade Tensions Escalation,macro,2025-07-28,2025-08-01,2025-07-28 to 2025-08-01,4
23,Market Volatility From Policy Shifts,macro,2024-12-16,2024-12-19,2024-12-16 to 2024-12-19,3
24,Market Volatility From Policy Shifts,macro,2025-02-25,2025-03-10,2025-02-25 to 2025-03-10,13
25,Market Volatility From Policy Shifts,macro,2025-03-24,2025-04-08,2025-03-24 to 2025-04-08,15
26,Market Volatility From Policy Shifts,macro,2025-07-28,2025-08-01,2025-07-28 to 2025-08-01,4
27,Market Volatility From Policy Shifts,macro,2025-09-09,2025-09-15,2025-09-09 to 2025-09-15,6
28,Revenue Miss Expectations Promotions Impact,micro,2024-10-08,2024-10-10,2024-10-08 to 2024-10-10,2
29,Revenue Miss Expectations Promotions Impact,micro,2024-10-14,2024-10-31,2024-10-14 to 2024-10-31,17
30,New Trading Tools Features Launch,micro,2024-10-10,2024-10-14,2024-10-10 to 2024-10-14,4
31,Revenue Miss Estimates Weaker Results,micro,2024-10-14,2024-10-31,2024-10-14 to 2024-10-31,17
32,Q3 Earnings Revenue Miss Expectations,micro,2024-10-31,2024-12-06,2024-10-31 to 2024-12-06,36
33,Technical Indicators Correction Warning,micro,2024-12-06,2024-12-10,2024-12-06 to 2024-12-10,4
34,Crypto Trading Expansion Gold Card Launch,micro,2024-12-10,2024-12-16,2024-12-10 to 2024-12-16,6
35,Business Expansion Customer Base Growth,micro,2024-12-19,2024-12-31,2024-12-19 to 2024-12-31,12
36,CEO Aggressive 2025 Expansion Plans,micro,2024-12-31,2025-01-06,2024-12-31 to 2025-01-06,6
37,SEC $45 Million Settlement Violations,micro,2025-01-06,2025-01-13,2025-01-06 to 2025-01-13,7
38,CME Group Futures Products Launch,micro,2025-01-13,2025-01-27,2025-01-13 to 2025-01-27,14
39,Q4 Earnings Beat Strong Profitability,micro,2025-01-27,2025-02-14,2025-01-27 to 2025-02-14,18
40,CQG Partnership Futures Infrastructure,micro,2025-02-14,2025-02-25,2025-02-14 to 2025-02-25,11
41,S&P 500 Inclusion Snubbed Expectations,micro,2025-07-18,2025-07-28,2025-07-18 to 2025-07-28,10
42,Bitcoin Rally Crypto Growth Optimism,micro,2025-08-08,2025-08-18,2025-08-08 to 2025-08-18,10
43,S&P 500 Index Addition,micro,2025-09-03,2025-09-09,2025-09-03 to 2025-09-09,6

In [4]:
# Debug: Check what keys are available
print(f"🔍 Available keys in result: {list(result.keys())}")

# Safely extract data with fallbacks
risk_share_index = result.get('risk_share_index', {})
macro_volatility_df = result.get('macro_volatility_df')
micro_volatility_df = result.get('micro_volatility_df')
impact_metrics_df = result.get('impact_metrics_df')
macro_total_impact_df = result.get('macro_total_impact_df')
micro_total_impact_df = result.get('micro_total_impact_df')
Factor_Risk_Reward = result.get('Factor_Risk_Reward')


# Show update time
if 'meta_info' in result:
    print(f"\n📅 Data Last Updated: {result['meta_info']['retrieved_date']}")
else:
    print("\n⚠️ No meta_info found in result")

🔍 Available keys in result: ['status', 'ticker', 'step1_result', 'step2_result', 'step3_result', 'step4_result', 'summary_df', 'macro_factors', 'micro_factors', 'risk_share_index', 'macro_volatility_df', 'micro_volatility_df', 'impact_metrics_df', 'macro_total_impact_df', 'micro_total_impact_df', 'Factor_Risk_Reward', 'factor_time_df', 'meta_info', 'date_ranges', 'storage_keys']

📅 Data Last Updated: 2025-10-08T00:49:50.136971

In [5]:
impact_metrics_df

,scope,factor,trend_count,weighted_mean,weighted_variance,average_duration,total_duration,trend_weight_score,score_weighted_mean,score_weighted_variance,risk_reward_ratio
0,macro,Fed Rate Cut Implementation,3,-0.000571,0.000057,6.666667,20,0.068182,-0.000039,3.890510e-06,0.075539
1,macro,Fed Rate Cut Signal No Timeline,1,0.000192,0.000019,16.000000,16,0.022727,0.000004,4.359114e-07,0.043795
2,macro,Fed Maintained Tight Monetary Policy,1,-0.028411,0.002841,7.000000,7,0.022727,-0.000646,6.456938e-05,0.533015
3,macro,Fed Held Rates Steady,1,0.006593,0.000659,14.000000,14,0.022727,0.000150,1.498446e-05,0.256772
4,macro,Trump 35% Tariffs Canada Multiple Countries,1,-0.014409,0.001441,4.000000,4,0.022727,-0.000327,3.274785e-05,0.379593
5,macro,Trump 25% Auto Tariffs Australia Goods,1,-0.030880,0.003088,15.000000,15,0.022727,-0.000702,7.018174e-05,0.555697
6,macro,Trump 25% Tariffs Mexico Canada Implemented,1,-0.015248,0.001525,13.000000,13,0.022727,-0.000347,3.465496e-05,0.390489
7,macro,Trump 100% Semiconductor Tariffs,1,0.011868,0.001187,7.000000,7,0.022727,0.000270,2.697202e-05,0.344495
8,macro,Tech Tariff Reprieve Announced,1,0.053201,0.005320,6.000000,6,0.022727,0.001209,1.209109e-04,0.729389
9,macro,Fed Rate Cut 25bps,2,-0.002645,0.000265,4.500000,9,0.045455,-0.000120,1.202389e-05,0.162642
10,macro,Fed Rate Cut 25 Basis Points,2,-0.002645,0.000265,4.500000,9,0.045455,-0.000120,1.202389e-05,0.162642
11,macro,Trade Policy Uncertainty Multiple Tariffs,3,-0.022471,0.002247,10.666667,32,0.068182,-0.001532,1.532093e-04,0.474033
12,macro,Monetary Policy Tightening Concerns,1,-0.028411,0.002841,7.000000,7,0.022727,-0.000646,6.456938e-05,0.533015
13,macro,Fed Rate Cut Expectations Unmet,1,0.000192,0.000019,16.000000,16,0.022727,0.000004,4.359114e-07,0.043795
14,macro,Global Trade Tensions Escalation,3,-0.022471,0.002247,10.666667,32,0.068182,-0.001532,1.532093e-04,0.474033
15,macro,Market Volatility From Policy Shifts,5,-0.018119,0.001812,8.200000,41,0.113636,-0.002059,2.058951e-04,0.425661
16,micro,Revenue Miss Expectations Promotions Impact,2,-0.004822,0.000723,9.500000,19,0.045455,-0.000219,3.287822e-05,0.179297
17,micro,New Trading Tools Features Launch,1,0.012016,0.001802,4.000000,4,0.022727,0.000273,4.096230e-05,0.283027
18,micro,Revenue Miss Estimates Weaker Results,1,-0.004407,0.000661,17.000000,17,0.022727,-0.000100,1.502437e-05,0.171409
19,micro,Q3 Earnings Revenue Miss Expectations,1,0.017771,0.002666,36.000000,36,0.022727,0.000404,6.058190e-05,0.344197
20,micro,Technical Indicators Correction Warning,1,-0.043218,0.006483,4.000000,4,0.022727,-0.000982,1.473350e-04,0.536770
21,micro,Crypto Trading Expansion Gold Card Launch,1,0.033260,0.004989,6.000000,6,0.022727,0.000756,1.133868e-04,0.470887
22,micro,Business Expansion Customer Base Growth,1,0.000547,0.000082,12.000000,12,0.022727,0.000012,1.865688e-06,0.060402
23,micro,CEO Aggressive 2025 Expansion Plans,1,0.033975,0.005096,6.000000,6,0.022727,0.000772,1.158242e-04,0.475921
24,micro,SEC $45 Million Settlement Violations,1,-0.004449,0.000667,7.000000,7,0.022727,-0.000101,1.516585e-05,0.172214
25,micro,CME Group Futures Products Launch,1,0.013637,0.002045,14.000000,14,0.022727,0.000310,4.648817e-05,0.301513
26,micro,Q4 Earnings Beat Strong Profitability,1,0.020517,0.003078,18.000000,18,0.022727,0.000466,6.994460e-05,0.369839
27,micro,CQG Partnership Futures Infrastructure,1,-0.046461,0.006969,11.000000,11,0.022727,-0.001056,1.583883e-04,0.556540
28,micro,S&P 500 Inclusion Snubbed Expectations,1,-0.010166,0.001525,10.000000,10,0.022727,-0.000231,3.465625e-05,0.260331
29,micro,Bitcoin Rally Crypto Growth Optimism,1,-0.002946,0.000442,10.000000,10,0.022727,-0.000067,1.004325e-05,0.140143
30,micro,S&P 500 Index Addition,1,0.037192,0.005579,6.000000,6,0.022727,0.000845,1.267922e-04,0.497945

In [6]:
from react_treemap_generator import generate_and_display_react_treemap

# Prepare data for treemap - using your existing DataFrames
macro_df = macro_total_impact_df.copy()


micro_df = micro_total_impact_df.copy() 


# Generate treemap HTML
html_content = generate_and_display_react_treemap(
    macro_df=macro_df,
    micro_df=micro_df,
    Factor_Risk_Reward_dataset=Factor_Risk_Reward,
    risk_share_index=risk_share_index,
    factor_time_df=factor_time_df,  # 🔧 FIX: Add factor_time_df for card flip functionality
    language="English",
    ticker=ticker
)

print("✅ Treemap generated and opened in browser!")

Q&Q.AI treemap with Risk Analysis opened in browser! Language: English
📊 Ticker: HOOD
✅ Portfolio overview removed
✅ Multilingual support added
✅ Risk share summary integrated
✅ Treemap generated and opened in browser!

### We check the previous update time

In [19]:
previous_update_time = result['meta_info']['retrieved_date']
previous_update_time

'2025-10-03T16:58:52.995458'

In [20]:
from datetime import datetime
fake_last_update = datetime(2025, 8, 10, 14, 30, 45, 123456).isoformat()
previous_update = fake_last_update

## Here is the update logic
#### Call the Quant Impact Update PY

In [21]:
import sys
import importlib
import asyncio
from datetime import datetime

# Remove cached modules
modules_to_remove = ['Quant_Impact_Update_Metrics']

for module_name in modules_to_remove:
    if module_name in sys.modules:
        del sys.modules[module_name]
        print(f"✅ Removed cached module: {module_name}")

from Quant_Impact_Update_Metrics import generate_update_metrics

print("✅ Successfully imported Quant_Impact_Update_Metrics")

✅ Removed cached module: Quant_Impact_Update_Metrics
✅ Successfully imported Quant_Impact_Update_Metrics

### Compare with previous update date, and current time

In [22]:

previous_update = previous_update

if 'T' in previous_update:
    previous_update_time = previous_update.split('T')[0]  
else:
    previous_update_time = previous_update

print(f"📅 Using date: {previous_update_time}")

New_impact_metrics_df, New_final_impact_metrics_df, New_factor_time_df = generate_update_metrics(
    ticker=ticker,
    previous_update_time=previous_update_time,
    language="English"
)

📅 Using date: 2025-08-10

================================================================================
🚀 Generating Update Metrics for PYPL
📅 From: 2025-08-10 to Today
================================================================================

📖 Step 1: Reading filtered stock trend data...
📅 Filtered trends: 7 periods from 2025-08-10 onwards
📊 Computing market beta from 2025-08-10 to 2025-10-05
   ✅ Market Beta: 1.1857

🔍 Step 2: Extracting factors...
   📊 Detected 7 trends → Generating 7 factors per scope
✅ Generated 7 macro factors
✅ Generated 7 micro factors

🗓️ Step 3: Mapping date ranges...
🔍 Step 2: Mapping MICRO + MACRO factors to date ranges for PYPL
✅ Mapped macro factors to date ranges
✅ Mapped micro factors to date ranges

⚖️ Step 4: Beta filtering...
🔍 Step 3: Beta filtering for PYPL
   Using SPY_return_rate from stock trend database
   Using market beta: 1.2777
   Risk-free rate: 2.5% annual
   Found 7 historical trend periods
   Processing date ranges from 2025-08-11 to 2025-10-01
   📊 Annual Volatility for PYPL: 0.2673 (26.73%)
   🔧 Volatility Factor (vol/15.874): 0.0168

 Processing 7 macro factors...
   ✅ Fed Rate Cut Expectation: 2 periods
   ✅ Fed Rate Cut Implementation: 1 periods
   ✅ Fed No Rate Cut Worse Than Expected: 1 periods
   ✅ Bitcoin Record Highs Better Than Expected: 1 periods
   ✅ USMCA Trade Deal Renegotiation Worse Than Expected: 1 periods
   ✅ PCE Inflation Data As Expected: 1 periods
   ✅ AI Bubble Concerns Worse Than Expected: 1 periods

 Processing 7 micro factors...
   ✅ Unbranded Processing Growth Bottoming Better Than Expected: 1 periods
   ✅ Branded Checkout TPV Growth As Expected: 1 periods
   ✅ Venmo Revenue Growth Better Than Expected: 1 periods
   ✅ Q2 Earnings Underperformance Worse Than Expected: 1 periods
   ✅ BNPL Volume Growth Better Than Expected: 2 periods
   ✅ Google AI Partnership Implementation: 2 periods
   ✅ Analyst Downgrade Worse Than Expected: 1 periods

✅ Beta filtering completed!
   Processed 7 macro factors
   Processed 7 micro factors
   Used SPY_return_rate from stock trend database
   Applied volatility normalization: 0.0168

📊 Step 5: Computing impact metrics...
🔍 Step 4: Generating impact metrics for PYPL

 Processing 7 macro factors...
   ✅ Fed Rate Cut Expectation: μ=0.0043, σ²=0.0004
   ✅ Fed Rate Cut Implementation: μ=0.0027, σ²=0.0003
   ✅ Fed No Rate Cut Worse Than Expected: μ=-0.0031, σ²=0.0003
   ✅ Bitcoin Record Highs Better Than Expected: μ=0.0090, σ²=0.0009
   ✅ USMCA Trade Deal Renegotiation Worse Than Expected: μ=0.0020, σ²=0.0002
   ✅ PCE Inflation Data As Expected: μ=0.0015, σ²=0.0002
   ✅ AI Bubble Concerns Worse Than Expected: μ=0.0046, σ²=0.0005

 Processing 7 micro factors...
   ✅ Unbranded Processing Growth Bottoming Better Than Expected: μ=0.0172, σ²=0.0026
   ✅ Branded Checkout TPV Growth As Expected: μ=0.0172, σ²=0.0026
   ✅ Venmo Revenue Growth Better Than Expected: μ=0.0172, σ²=0.0026
   ✅ Q2 Earnings Underperformance Worse Than Expected: μ=-0.0043, σ²=0.0006
   ✅ BNPL Volume Growth Better Than Expected: μ=0.0016, σ²=0.0002
   ✅ Google AI Partnership Implementation: μ=0.0026, σ²=0.0004
   ✅ Analyst Downgrade Worse Than Expected: μ=-0.0043, σ²=0.0006

🔧 Step 6: Calculating missing metrics...

🎯 Step 7: Generating final impact metrics...
🔍 Letting LLM analyze dataset and classify factors...
🤖 Calling LLM to analyze dataset...
✅ Schema Generated!
📊 Macro: 2 groups
📊 Micro: 2 groups
📊 Sector: 0 groups
🔄 Converting schema to compound datasets...
📊 Compound Dataset Generated!
   Total factor categories: 4

================================================================================
✅ Update Metrics Generated Successfully!
================================================================================

📊 Final Impact Metrics: 4 factors
📅 Factor Time Mappings: 17 intervals

### These are new factor time

In [23]:
New_factor_time_df

,factor_name,scope,start_date,end_date,time_interval,duration_days
0,Fed Rate Cut Expectation,macro,2025-08-11,2025-08-13,2025-08-11 to 2025-08-13,2
1,Fed Rate Cut Expectation,macro,2025-08-21,2025-08-29,2025-08-21 to 2025-08-29,8
2,Fed Rate Cut Implementation,macro,2025-09-10,2025-09-17,2025-09-10 to 2025-09-17,7
3,Fed No Rate Cut Worse Than Expected,macro,2025-08-13,2025-08-21,2025-08-13 to 2025-08-21,8
4,Bitcoin Record Highs Better Than Expected,macro,2025-08-11,2025-08-13,2025-08-11 to 2025-08-13,2
5,USMCA Trade Deal Renegotiation Worse Than Expe...,macro,2025-08-29,2025-09-10,2025-08-29 to 2025-09-10,12
6,PCE Inflation Data As Expected,macro,2025-09-17,2025-09-29,2025-09-17 to 2025-09-29,12
7,AI Bubble Concerns Worse Than Expected,macro,2025-09-29,2025-10-01,2025-09-29 to 2025-10-01,2
8,Unbranded Processing Growth Bottoming Better T...,micro,2025-08-11,2025-08-13,2025-08-11 to 2025-08-13,2
9,Branded Checkout TPV Growth As Expected,micro,2025-08-11,2025-08-13,2025-08-11 to 2025-08-13,2
10,Venmo Revenue Growth Better Than Expected,micro,2025-08-11,2025-08-13,2025-08-11 to 2025-08-13,2
11,Q2 Earnings Underperformance Worse Than Expected,micro,2025-08-13,2025-08-21,2025-08-13 to 2025-08-21,8
12,BNPL Volume Growth Better Than Expected,micro,2025-08-21,2025-08-29,2025-08-21 to 2025-08-29,8
13,BNPL Volume Growth Better Than Expected,micro,2025-09-17,2025-09-29,2025-09-17 to 2025-09-29,12
14,Google AI Partnership Implementation,micro,2025-09-10,2025-09-17,2025-09-10 to 2025-09-17,7
15,Google AI Partnership Implementation,micro,2025-09-17,2025-09-29,2025-09-17 to 2025-09-29,12
16,Analyst Downgrade Worse Than Expected,micro,2025-08-13,2025-08-21,2025-08-13 to 2025-08-21,8

In [25]:
New_final_impact_metrics_df

,category,factor_name,max_compound_return,min_compound_return,max_min_ratio,return_range,sub_factor_count,sub_factors,row_numbers,weighted_means,avg_durations,compound_returns
0,Micro,Company Performance,0.034771,-0.033546,-1.036495,0.068317,5,Unbranded Processing Growth Bottoming Better T...,"[7, 8, 9, 10, 13]","[0.0172, 0.0172, 0.0172, ...], +2 more","[2.0, 2.0, 2.0, ...], +2 more","[0.035, 0.035, 0.035, ...], +2 more"
1,Micro,Strategic Partnerships,0.025368,0.016478,1.539504,0.008890,2,BNPL Volume Growth Better Than Expected | Goog...,"[11, 12]","[0.0016, 0.0026]","[10.0, 9.5]","[0.016, 0.025]"
2,Macro,Economic Indicators,0.024419,0.009157,2.666830,0.015263,4,Bitcoin Record Highs Better Than Expected | US...,"[3, 4, 5, 6]","[0.0090, 0.0020, 0.0015, ...], +1 more","[2.0, 12.0, 12.0, ...], +1 more","[0.018, 0.024, 0.018, ...], +1 more"
3,Macro,Monetary Policy,0.021853,-0.024719,-0.884039,0.046572,3,Fed Rate Cut Expectation | Fed Rate Cut Implem...,"[0, 1, 2]","[0.0043, 0.0027, -0.0031, ...]","[5.0, 7.0, 8.0, ...]","[0.022, 0.019, -0.025, ...]"

In [26]:
Factor_Risk_Reward

,category,factor_name,max_compound_return,min_compound_return,max_min_ratio,return_range,sub_factor_count,sub_factors,row_numbers,weighted_means,avg_durations,compound_returns
0,Macro,Trade Policy,0.117255,-0.066756,-1.756457,0.184011,2,Trump Tariff Implementation | Trump Tariff Relief,"[3, 4]","[-0.0052, 0.0061]","[13.2, 18.2]","[-0.067, 0.117]"
1,Macro,Economic Indicators,0.097411,-0.053491,-1.821083,0.150902,5,Geopolitical Tension Escalation | Strong Jobs ...,"[5, 6, 7, 9, 10]","[-0.0035, 0.0062, 0.0019, ...], +2 more","[6.0, 15.0, 7.0, ...], +2 more","[-0.021, 0.097, 0.013, ...], +2 more"
2,Macro,Monetary Policy,0.089905,-0.042907,-2.095328,0.132812,4,Fed Rate Cut Expectation | Fed Rate Cut Better...,"[0, 1, 2, 8]","[0.0037, 0.0072, -0.0217, ...], +1 more","[8.4, 12.0, 2.0, ...], +1 more","[0.032, 0.090, -0.043, ...], +1 more"
3,Micro,Financial Performance,0.070437,-0.260365,-0.270532,0.330802,8,Earnings Beat Better Than Expected | Earnings ...,"[11, 12, 13, 14, 15, 16, 20, 21]","[0.0027, -0.0083, 0.0024, ...], +5 more","[12.8, 10.4, 28.0, ...], +5 more","[0.034, -0.083, 0.070, ...], +5 more"
4,Micro,Strategic Initiatives,0.059112,0.036940,1.600230,0.022172,2,Strategic Partnership Announcement | Product I...,"[22, 23]","[0.0037, 0.0031]","[15.5, 11.6]","[0.059, 0.037]"
5,Micro,Operational Metrics,0.032490,-0.189638,-0.171328,0.222129,3,Payment Volume Growth Better Than Expected | P...,"[17, 18, 19]","[0.0030, -0.0144, 0.0046, ...]","[10.2, 14.5, 7.0, ...]","[0.032, -0.190, 0.032, ...]"

In [27]:
impact_metrics_df

,scope,factor,trend_count,weighted_mean,weighted_variance,average_duration,total_duration,trend_weight_score,score_weighted_mean,score_weighted_variance,risk_reward_ratio
0,macro,Fed Rate Cut Expectation,5,0.003749,0.000375,8.400000,42,0.079365,0.000298,0.000030,0.193623
1,macro,Fed Rate Cut Better Than Expected,1,0.007200,0.000720,12.000000,12,0.015873,0.000114,0.000011,0.268328
2,macro,Fed Rate Cut Worse Than Expected,1,-0.021689,0.002169,2.000000,2,0.015873,-0.000344,0.000034,0.465712
3,macro,Trump Tariff Implementation,4,-0.005201,0.000520,13.250000,53,0.063492,-0.000330,0.000033,0.228050
4,macro,Trump Tariff Relief,4,0.006094,0.000609,18.250000,73,0.063492,0.000387,0.000039,0.246856
5,macro,Geopolitical Tension Escalation,2,-0.003507,0.000351,6.000000,12,0.031746,-0.000111,0.000011,0.187274
6,macro,Strong Jobs Report Better Than Expected,1,0.006216,0.000622,15.000000,15,0.015873,0.000099,0.000010,0.249322
7,macro,Weak Jobs Report Worse Than Expected,2,0.001916,0.000192,7.000000,14,0.031746,0.000061,0.000006,0.138412
8,macro,Bond Yields Rising,1,-0.010713,0.001071,4.000000,4,0.015873,-0.000170,0.000017,0.327313
9,macro,Market Volatility Increase,3,-0.003919,0.000392,14.000000,42,0.047619,-0.000187,0.000019,0.197966
10,macro,Market Volatility Decrease,2,0.005957,0.000596,9.500000,19,0.031746,0.000189,0.000019,0.244061
11,micro,Earnings Beat Better Than Expected,4,0.002663,0.000399,12.750000,51,0.063492,0.000169,0.000025,0.133232
12,micro,Earnings Miss Worse Than Expected,5,-0.008303,0.001245,10.400000,52,0.079365,-0.000659,0.000099,0.235271
13,micro,Revenue Growth Better Than Expected,1,0.002434,0.000365,28.000000,28,0.015873,0.000039,0.000006,0.127382
14,micro,Revenue Growth Worse Than Expected,2,-0.016289,0.002443,5.000000,10,0.031746,-0.000517,0.000078,0.329534
15,micro,Guidance Raise Better Than Expected,1,-0.029432,0.004415,4.000000,4,0.015873,-0.000467,0.000070,0.442960
16,micro,Guidance Cut Worse Than Expected,1,-0.013945,0.002092,4.000000,4,0.015873,-0.000221,0.000033,0.304900
17,micro,Payment Volume Growth Better Than Expected,4,0.003046,0.000457,10.250000,41,0.063492,0.000193,0.000029,0.142508
18,micro,Payment Volume Growth Worse Than Expected,2,-0.014397,0.002160,14.500000,29,0.031746,-0.000457,0.000069,0.309807
19,micro,Active Account Growth Better Than Expected,1,0.004578,0.000687,7.000000,7,0.015873,0.000073,0.000011,0.174702
20,micro,Profit Margin Expansion Better Than Expected,2,0.001903,0.000285,19.500000,39,0.031746,0.000060,0.000009,0.112627
21,micro,Profit Margin Contraction Worse Than Expected,1,-0.011991,0.001799,25.000000,25,0.015873,-0.000190,0.000029,0.282742
22,micro,Strategic Partnership Announcement,6,0.003712,0.000557,15.500000,93,0.095238,0.000354,0.000053,0.157312
23,micro,Product Innovation Launch,7,0.003140,0.000471,11.571429,81,0.111111,0.000349,0.000052,0.144676

## LLM Agent Mapping the Old/New/Pre-exist Factor to update the impaction metrics

### Stpe 1). LLM Retrieve the Similar Previous Exist Factors / Directly Add this New Factor

In [28]:
"""
Quant Impact Factor Mapping Pipeline
====================================

This module provides functions to merge new and old impact metrics using LLM-based factor mapping.
It extracts factor names, uses LLM to map similar factors, and merges the results.

Usage:
------
from Quant_Impact_Factor_Mapping import merge_impact_metrics

# Merge new and old impact metrics
merged_df = merge_impact_metrics(
    new_impact_df=new_impact_df,
    old_impact_metrics_df=old_impact_metrics_df,
    ticker="AAPL"
)
"""

import pandas as pd
import json
from typing import List, Dict, Tuple, Any
from LLM_Call_Agent import LLMCallAgent


def extract_factor_names(impact_df: pd.DataFrame) -> List[str]:
    """
    Extract factor names from impact metrics DataFrame.
    
    Args:
        impact_df: DataFrame with impact metrics
        
    Returns:
        List of factor names
    """
    if 'factor' in impact_df.columns:
        return impact_df['factor'].tolist()
    elif 'factor_name' in impact_df.columns:
        return impact_df['factor_name'].tolist()
    elif impact_df.index.name == 'factor_name':
        return impact_df.index.tolist()
    else:
        # Try to extract from index if it's a string index
        return [str(idx) for idx in impact_df.index]


def map_factors_with_llm(
    new_factors: List[str], 
    old_factors: List[str], 
    ticker: str
) -> Dict[str, Any]:
    """
    Use LLM to map new factors to old factors or identify new ones.
    
    Args:
        new_factors: List of new factor names
        old_factors: List of old factor names
        ticker: Stock ticker for context
        
    Returns:
        Dictionary with mapping results
    """
    llm_agent = LLMCallAgent()
    
    prompt = f"""
You are a financial factor mapping expert. I need you to map new factors to existing factors for {ticker} stock analysis.

EXISTING FACTORS:
{json.dumps(old_factors, indent=2)}

NEW FACTORS:
{json.dumps(new_factors, indent=2)}

TASK:
1. For each new factor, determine if it's similar to any existing factor
2. If similar, provide the index of the existing factor (0-based)
3. If not similar, mark it as "new"

OUTPUT FORMAT (JSON):
{{
    "mappings": [
        {{
            "new_factor": "factor_name",
            "type": "existing" or "new",
            "existing_index": 0,  // only if type is "existing"
            "existing_factor": "existing_factor_name"  // only if type is "existing"
        }}
    ]
}}

RULES:
- Be conservative: only map if factors are clearly similar (same concept, different wording)
- Consider synonyms, abbreviations, and different phrasings
- If unsure, mark as "new"
- Focus on financial and market impact concepts
"""
    
    try:
        response = llm_agent.call_deepseek(prompt)
        
        # Parse JSON response
        if isinstance(response, str):
            # Try to extract JSON from response
            start_idx = response.find('{')
            end_idx = response.rfind('}') + 1
            if start_idx != -1 and end_idx != 0:
                json_str = response[start_idx:end_idx]
                result = json.loads(json_str)
            else:
                raise ValueError("No valid JSON found in response")
        else:
            result = response
            
        return result
        
    except Exception as e:
        print(f"❌ LLM mapping failed: {e}")
        # Fallback: mark all as new
        return {
            "mappings": [
                {
                    "new_factor": factor,
                    "type": "new"
                }
                for factor in new_factors
            ]
        }


def merge_impact_metrics(
    new_impact_df: pd.DataFrame,
    old_impact_metrics_df: pd.DataFrame,
    ticker: str
) -> pd.DataFrame:
    """
    Merge new and old impact metrics using LLM-based factor mapping.
    Only keeps essential columns and adds new factors as rows.
    
    Args:
        new_impact_df: New impact metrics DataFrame
        old_impact_metrics_df: Old impact metrics DataFrame
        ticker: Stock ticker for context
        
    Returns:
        Clean merged impact metrics DataFrame
    """
    print(f"🔄 Merging impact metrics for {ticker}...")
    
    # Extract factor names
    new_factors = extract_factor_names(new_impact_df)
    old_factors = extract_factor_names(old_impact_metrics_df)
    
    print(f"📊 New factors: {len(new_factors)}")
    print(f"📊 Old factors: {len(old_factors)}")
    
    # Get LLM mapping
    print("🤖 Getting LLM factor mapping...")
    mapping_result = map_factors_with_llm(new_factors, old_factors, ticker)
    
    # Start with old impact metrics as base - keep only essential columns
    essential_columns = [
        'scope', 'factor', 'trend_count', 'weighted_mean', 'weighted_variance',
        'average_duration', 'total_duration', 'trend_weight_score',
        'score_weighted_mean', 'score_weighted_variance', 'risk_reward_ratio'
    ]
    
    # Filter to only keep essential columns that exist
    available_columns = [col for col in essential_columns if col in old_impact_metrics_df.columns]
    merged_df = old_impact_metrics_df[available_columns].copy()
    
    # Add mapping column
    merged_df['mapping_new_factors'] = ""
    
    # Process each new factor
    for mapping in mapping_result.get('mappings', []):
        new_factor = mapping['new_factor']
        mapping_type = mapping['type']
        
        if mapping_type == 'existing':
            # Map to existing factor
            existing_index = mapping['existing_index']
            existing_factor = mapping['existing_factor']
            
            print(f"✅ Mapping '{new_factor}' → '{existing_factor}' (index {existing_index})")
            
            # Add to mapping column
            if merged_df.iloc[existing_index]['mapping_new_factors']:
                merged_df.iloc[existing_index, merged_df.columns.get_loc('mapping_new_factors')] += f", {new_factor}"
            else:
                merged_df.iloc[existing_index, merged_df.columns.get_loc('mapping_new_factors')] = new_factor
                
        elif mapping_type == 'new':
            # Add as new row
            print(f"➕ Adding new factor: '{new_factor}'")
            
            # Get the new factor's data - handle both 'factor' and 'factor_name' columns
            if 'factor' in new_impact_df.columns:
                new_factor_data = new_impact_df[new_impact_df['factor'] == new_factor].iloc[0]
            elif 'factor_name' in new_impact_df.columns:
                new_factor_data = new_impact_df[new_impact_df['factor_name'] == new_factor].iloc[0]
            else:
                print(f"❌ Cannot find factor column in new_impact_df")
                continue
            
            # Create new row with only essential columns
            new_row = {}
            for col in available_columns:
                if col in new_factor_data:
                    new_row[col] = new_factor_data[col]
                else:
                    new_row[col] = None  # Fill missing columns with None
            
            new_row['mapping_new_factors'] = ""
            
            # Add to merged DataFrame
            merged_df = pd.concat([merged_df, pd.DataFrame([new_row])], ignore_index=True)
    
    print(f"✅ Merge completed: {len(merged_df)} total factors")
    print(f"📋 Columns kept: {list(merged_df.columns)}")
    return merged_df


def get_factor_mapping_summary(merged_df: pd.DataFrame) -> Dict[str, Any]:
    """
    Get summary of factor mappings.
    
    Args:
        merged_df: Merged impact metrics DataFrame
        
    Returns:
        Dictionary with mapping summary
    """
    total_factors = len(merged_df)
    mapped_factors = len(merged_df[merged_df['mapping_new_factors'] != ""])
    new_factors = total_factors - len(merged_df[merged_df['mapping_new_factors'] != ""])
    
    return {
        "total_factors": total_factors,
        "mapped_factors": mapped_factors,
        "new_factors": new_factors,
        "mapping_rate": mapped_factors / total_factors if total_factors > 0 else 0
    }

In [18]:
# Merge impact metrics
merged_df = merge_impact_metrics(
    new_impact_df=New_impact_metrics_df,
    old_impact_metrics_df=impact_metrics_df,
    ticker=ticker
)

🔄 Merging impact metrics for PYPL...
📊 New factors: 14
📊 Old factors: 24
🤖 Getting LLM factor mapping...
✅ Mapping 'Fed Rate Cut Expectation' → 'Fed Rate Cut Expectation' (index 0)
➕ Adding new factor: 'Fed Rate Cut Implementation'
➕ Adding new factor: 'Fed Policy Uncertainty Worse Than Expected'
➕ Adding new factor: 'Bitcoin Record Highs Better Than Expected'
➕ Adding new factor: 'USMCA Trade Deal Renegotiation Worse Than Expected'
➕ Adding new factor: 'PCE Inflation Data As Expected'
➕ Adding new factor: 'Market Bubble Concerns Worse Than Expected'
➕ Adding new factor: 'Unbranded Processing Growth Bottoming Better Than Expected'
✅ Mapping 'Branded Checkout TPV Growth As Expected' → 'Payment Volume Growth Better Than Expected' (index 17)
✅ Mapping 'Venmo Revenue Growth Better Than Expected' → 'Revenue Growth Better Than Expected' (index 13)
✅ Mapping 'Q2 Earnings Underperformance Worse Than Expected' → 'Earnings Miss Worse Than Expected' (index 12)
✅ Mapping 'BNPL Volume Growth Better Than Expected' → 'Payment Volume Growth Better Than Expected' (index 17)
✅ Mapping 'Google AI Partnership Implementation' → 'Strategic Partnership Announcement' (index 23)
➕ Adding new factor: 'Analyst Downgrade Worse Than Expected'
✅ Merge completed: 32 total factors
📋 Columns kept: ['scope', 'factor', 'trend_count', 'weighted_mean', 'weighted_variance', 'average_duration', 'total_duration', 'trend_weight_score', 'score_weighted_mean', 'score_weighted_variance', 'risk_reward_ratio', 'mapping_new_factors']

In [35]:
merged_df

,scope,factor,trend_count,weighted_mean,weighted_variance,average_duration,total_duration,trend_weight_score,score_weighted_mean,score_weighted_variance,risk_reward_ratio,mapping_new_factors
0,macro,Fed Rate Cut Expectation,5,0.003749,0.000375,8.400000,42,0.079365,0.000298,0.000030,0.193623,Fed Rate Cut Expectation
1,macro,Fed Rate Cut Better Than Expected,1,0.007200,0.000720,12.000000,12,0.015873,0.000114,0.000011,0.268328,
2,macro,Fed Rate Cut Worse Than Expected,1,-0.021689,0.002169,2.000000,2,0.015873,-0.000344,0.000034,0.465712,
3,macro,Trump Tariff Implementation,4,-0.005201,0.000520,13.250000,53,0.063492,-0.000330,0.000033,0.228050,
4,macro,Trump Tariff Relief,4,0.006094,0.000609,18.250000,73,0.063492,0.000387,0.000039,0.246856,
5,macro,Geopolitical Tension Escalation,2,-0.003507,0.000351,6.000000,12,0.031746,-0.000111,0.000011,0.187274,
6,macro,Strong Jobs Report Better Than Expected,1,0.006216,0.000622,15.000000,15,0.015873,0.000099,0.000010,0.249322,
7,macro,Weak Jobs Report Worse Than Expected,2,0.001916,0.000192,7.000000,14,0.031746,0.000061,0.000006,0.138412,
8,macro,Bond Yields Rising,1,-0.010713,0.001071,4.000000,4,0.015873,-0.000170,0.000017,0.327313,
9,macro,Market Volatility Increase,3,-0.003919,0.000392,14.000000,42,0.047619,-0.000187,0.000019,0.197966,
10,macro,Market Volatility Decrease,2,0.005957,0.000596,9.500000,19,0.031746,0.000189,0.000019,0.244061,
11,micro,Earnings Beat Better Than Expected,4,0.002663,0.000399,12.750000,51,0.063492,0.000169,0.000025,0.133232,
12,micro,Earnings Miss Worse Than Expected,5,-0.008303,0.001245,10.400000,52,0.079365,-0.000659,0.000099,0.235271,Q2 Earnings Underperformance Worse Than Expected
13,micro,Revenue Growth Better Than Expected,1,0.002434,0.000365,28.000000,28,0.015873,0.000039,0.000006,0.127382,Venmo Revenue Growth Better Than Expected
14,micro,Revenue Growth Worse Than Expected,2,-0.016289,0.002443,5.000000,10,0.031746,-0.000517,0.000078,0.329534,
15,micro,Guidance Raise Better Than Expected,1,-0.029432,0.004415,4.000000,4,0.015873,-0.000467,0.000070,0.442960,
16,micro,Guidance Cut Worse Than Expected,1,-0.013945,0.002092,4.000000,4,0.015873,-0.000221,0.000033,0.304900,
17,micro,Payment Volume Growth Better Than Expected,4,0.003046,0.000457,10.250000,41,0.063492,0.000193,0.000029,0.142508,"Branded Checkout TPV Growth As Expected, BNPL ..."
18,micro,Payment Volume Growth Worse Than Expected,2,-0.014397,0.002160,14.500000,29,0.031746,-0.000457,0.000069,0.309807,
19,micro,Active Account Growth Better Than Expected,1,0.004578,0.000687,7.000000,7,0.015873,0.000073,0.000011,0.174702,
20,micro,Profit Margin Expansion Better Than Expected,2,0.001903,0.000285,19.500000,39,0.031746,0.000060,0.000009,0.112627,
21,micro,Profit Margin Contraction Worse Than Expected,1,-0.011991,0.001799,25.000000,25,0.015873,-0.000190,0.000029,0.282742,
22,micro,Strategic Partnership Announcement,6,0.003712,0.000557,15.500000,93,0.095238,0.000354,0.000053,0.157312,
23,micro,Product Innovation Launch,7,0.003140,0.000471,11.571429,81,0.111111,0.000349,0.000052,0.144676,Google AI Partnership Implementation
24,macro,Fed Rate Cut Implementation,1,0.002715,0.000272,7.000000,7,0.058824,0.000160,0.000016,0.164780,
25,macro,Fed Policy Uncertainty Worse Than Expected,1,-0.003124,0.000312,8.000000,8,0.058824,-0.000184,0.000018,0.176744,
26,macro,Bitcoin Record Highs Better Than Expected,1,0.008963,0.000896,2.000000,2,0.058824,0.000527,0.000053,0.299386,
27,macro,USMCA Trade Deal Renegotiation Worse Than Expe...,1,0.002013,0.000201,12.000000,12,0.058824,0.000118,0.000012,0.141863,
28,macro,PCE Inflation Data As Expected,1,0.001527,0.000153,12.000000,12,0.058824,0.000090,0.000009,0.123572,
29,macro,Market Bubble Concerns Worse Than Expected,1,0.004568,0.000457,2.000000,2,0.058824,0.000269,0.000027,0.213727,
30,micro,Unbranded Processing Growth Bottoming Better T...,1,0.017237,0.002586,2.000000,2,0.058824,0.001014,0.000152,0.338987,
31,micro,Analyst Downgrade Worse Than Expected,1,-0.004256,0.000638,8.000000,8,0.058824,-0.000250,0.000038,0.168447,

#### Step 2). Use Fix Key - Mapping Factor Name to retrieve old_new weight -> Update weight and variance

In [30]:
def update_impact_metrics_with_new_factors(merged_df: pd.DataFrame, new_impact_df: pd.DataFrame) -> pd.DataFrame:
    """
    Update impact metrics for factors that have new factor mappings.
    Recalculate weighted metrics based on old and new data.
    
    Args:
        merged_df: Merged DataFrame with mapping_new_factors column
        new_impact_df: New impact metrics DataFrame
        
    Returns:
        Updated impact metrics DataFrame
    """
    print("🔄 Updating impact metrics with new factor data...")
    
    updated_df = merged_df.copy()
    
    # Process each row that has new factor mappings
    for idx, row in updated_df.iterrows():
        if row['mapping_new_factors'] and row['mapping_new_factors'] != '':
            # Get the new factor names
            new_factors = [factor.strip() for factor in row['mapping_new_factors'].split(',')]
            
            print(f"📊 Updating factor: {row['factor']} with new factors: {new_factors}")
            
            # Get new factor data
            new_factor_data = []
            for new_factor in new_factors:
                if 'factor' in new_impact_df.columns:
                    new_data = new_impact_df[new_impact_df['factor'] == new_factor]
                elif 'factor_name' in new_impact_df.columns:
                    new_data = new_impact_df[new_impact_df['factor_name'] == new_factor]
                else:
                    continue
                
                if not new_data.empty:
                    new_factor_data.append(new_data.iloc[0])
            
            if not new_factor_data:
                continue
            
            # Calculate old metrics
            old_weighted_mean = row['weighted_mean']
            old_weighted_variance = row['weighted_variance']
            old_total_duration = row['total_duration']
            old_trend_count = row['trend_count']
            
            # Calculate new metrics
            new_total_duration = sum([data['total_duration'] for data in new_factor_data])
            new_trend_count = sum([data['trend_count'] for data in new_factor_data])
            new_weighted_mean = sum([data['weighted_mean'] * data['total_duration'] for data in new_factor_data]) / new_total_duration if new_total_duration > 0 else 0
            new_weighted_variance = sum([data['weighted_variance'] * data['total_duration'] for data in new_factor_data]) / new_total_duration if new_total_duration > 0 else 0
            
            # Calculate combined metrics using weighted average
            combined_total_duration = old_total_duration + new_total_duration
            old_weight = old_total_duration / combined_total_duration if combined_total_duration > 0 else 0
            new_weight = new_total_duration / combined_total_duration if combined_total_duration > 0 else 0
            
            # Update weighted mean and variance
            updated_weighted_mean = old_weight * old_weighted_mean + new_weight * new_weighted_mean
            updated_weighted_variance = old_weight * old_weighted_variance + new_weight * new_weighted_variance
            
            # Update other metrics
            updated_trend_count = old_trend_count + new_trend_count
            updated_average_duration = combined_total_duration / updated_trend_count if updated_trend_count > 0 else 0
            
            # Update trend weight score (assuming it's based on trend count)
            updated_trend_weight_score = updated_trend_count / (updated_trend_count + 1)  # Normalize
            
            # Update score weighted mean and variance
            updated_score_weighted_mean = updated_trend_weight_score * updated_weighted_mean
            updated_score_weighted_variance = updated_trend_weight_score * updated_weighted_variance
            
            # Update risk reward ratio (assuming it's based on weighted mean and variance)
            updated_risk_reward_ratio = abs(updated_weighted_mean) / (updated_weighted_variance ** 0.5) if updated_weighted_variance > 0 else 0
            
            # Update the row
            updated_df.at[idx, 'trend_count'] = updated_trend_count
            updated_df.at[idx, 'weighted_mean'] = updated_weighted_mean
            updated_df.at[idx, 'weighted_variance'] = updated_weighted_variance
            updated_df.at[idx, 'average_duration'] = updated_average_duration
            updated_df.at[idx, 'total_duration'] = combined_total_duration
            updated_df.at[idx, 'trend_weight_score'] = updated_trend_weight_score
            updated_df.at[idx, 'score_weighted_mean'] = updated_score_weighted_mean
            updated_df.at[idx, 'score_weighted_variance'] = updated_score_weighted_variance
            updated_df.at[idx, 'risk_reward_ratio'] = updated_risk_reward_ratio
            
            print(f"✅ Updated {row['factor']}: mean={updated_weighted_mean:.6f}, variance={updated_weighted_variance:.6f}")
    
    print(f"✅ Impact metrics update completed for {len(updated_df)} factors")
    return updated_df

In [31]:
# Update impact metrics with new factor data
updated_impact_metrics = update_impact_metrics_with_new_factors(
    merged_df=merged_df,
    new_impact_df=New_impact_metrics_df
)

🔄 Updating impact metrics with new factor data...
📊 Updating factor: Fed Rate Cut Expectation with new factors: ['Fed Rate Cut Expectation']
✅ Updated Fed Rate Cut Expectation: mean=0.003861, variance=0.000386
📊 Updating factor: Earnings Miss Worse Than Expected with new factors: ['Q2 Earnings Underperformance Worse Than Expected']
✅ Updated Earnings Miss Worse Than Expected: mean=-0.007763, variance=0.001164
📊 Updating factor: Revenue Growth Better Than Expected with new factors: ['Venmo Revenue Growth Better Than Expected']
✅ Updated Revenue Growth Better Than Expected: mean=0.003421, variance=0.000513
📊 Updating factor: Payment Volume Growth Better Than Expected with new factors: ['Branded Checkout TPV Growth As Expected', 'BNPL Volume Growth Better Than Expected']
✅ Updated Payment Volume Growth Better Than Expected: mean=0.003049, variance=0.000457
📊 Updating factor: Product Innovation Launch with new factors: ['Google AI Partnership Implementation']
✅ Updated Product Innovation Launch: mean=0.003045, variance=0.000457
✅ Impact metrics update completed for 32 factors

In [32]:
# 🧹 CLEANUP FUNCTION: Remove mapping_new_factors column after processing
def cleanup_impact_metrics_df(df: pd.DataFrame) -> pd.DataFrame:
    """
    Clean up the impact metrics DataFrame by removing temporary columns.
    
    Args:
        df: DataFrame with potential temporary columns
        
    Returns:
        Cleaned DataFrame
    """
    cleaned_df = df.copy()
    
    # Remove mapping_new_factors column if it exists
    if 'mapping_new_factors' in cleaned_df.columns:
        cleaned_df = cleaned_df.drop('mapping_new_factors', axis=1)
        print("🧹 Cleaned up: Removed 'mapping_new_factors' column")
    
    # Remove any other temporary columns if needed
    temp_columns = ['temp_', 'mapping_', '_temp']
    columns_to_remove = [col for col in cleaned_df.columns if any(temp in col for temp in temp_columns)]
    
    if columns_to_remove:
        cleaned_df = cleaned_df.drop(columns_to_remove, axis=1)
        print(f"🧹 Cleaned up: Removed temporary columns: {columns_to_remove}")
    
    print(f"✅ DataFrame cleaned: {len(df.columns)} → {len(cleaned_df.columns)} columns")
    return cleaned_df

# Test the cleanup function
print("🧪 Testing cleanup function...")
cleaned_impact_metrics_df = cleanup_impact_metrics_df(impact_metrics_df)
print(f"✅ Cleanup completed!")

🧪 Testing cleanup function...
✅ DataFrame cleaned: 11 → 11 columns
✅ Cleanup completed!

In [38]:
Update_Impact_Metrics_df = cleaned_impact_metrics_df
Update_Impact_Metrics_df

,scope,factor,trend_count,weighted_mean,weighted_variance,average_duration,total_duration,trend_weight_score,score_weighted_mean,score_weighted_variance,risk_reward_ratio
0,macro,Fed Rate Cut Expectation,5,0.003749,0.000375,8.400000,42,0.079365,0.000298,0.000030,0.193623
1,macro,Fed Rate Cut Better Than Expected,1,0.007200,0.000720,12.000000,12,0.015873,0.000114,0.000011,0.268328
2,macro,Fed Rate Cut Worse Than Expected,1,-0.021689,0.002169,2.000000,2,0.015873,-0.000344,0.000034,0.465712
3,macro,Trump Tariff Implementation,4,-0.005201,0.000520,13.250000,53,0.063492,-0.000330,0.000033,0.228050
4,macro,Trump Tariff Relief,4,0.006094,0.000609,18.250000,73,0.063492,0.000387,0.000039,0.246856
5,macro,Geopolitical Tension Escalation,2,-0.003507,0.000351,6.000000,12,0.031746,-0.000111,0.000011,0.187274
6,macro,Strong Jobs Report Better Than Expected,1,0.006216,0.000622,15.000000,15,0.015873,0.000099,0.000010,0.249322
7,macro,Weak Jobs Report Worse Than Expected,2,0.001916,0.000192,7.000000,14,0.031746,0.000061,0.000006,0.138412
8,macro,Bond Yields Rising,1,-0.010713,0.001071,4.000000,4,0.015873,-0.000170,0.000017,0.327313
9,macro,Market Volatility Increase,3,-0.003919,0.000392,14.000000,42,0.047619,-0.000187,0.000019,0.197966
10,macro,Market Volatility Decrease,2,0.005957,0.000596,9.500000,19,0.031746,0.000189,0.000019,0.244061
11,micro,Earnings Beat Better Than Expected,4,0.002663,0.000399,12.750000,51,0.063492,0.000169,0.000025,0.133232
12,micro,Earnings Miss Worse Than Expected,5,-0.008303,0.001245,10.400000,52,0.079365,-0.000659,0.000099,0.235271
13,micro,Revenue Growth Better Than Expected,1,0.002434,0.000365,28.000000,28,0.015873,0.000039,0.000006,0.127382
14,micro,Revenue Growth Worse Than Expected,2,-0.016289,0.002443,5.000000,10,0.031746,-0.000517,0.000078,0.329534
15,micro,Guidance Raise Better Than Expected,1,-0.029432,0.004415,4.000000,4,0.015873,-0.000467,0.000070,0.442960
16,micro,Guidance Cut Worse Than Expected,1,-0.013945,0.002092,4.000000,4,0.015873,-0.000221,0.000033,0.304900
17,micro,Payment Volume Growth Better Than Expected,4,0.003046,0.000457,10.250000,41,0.063492,0.000193,0.000029,0.142508
18,micro,Payment Volume Growth Worse Than Expected,2,-0.014397,0.002160,14.500000,29,0.031746,-0.000457,0.000069,0.309807
19,micro,Active Account Growth Better Than Expected,1,0.004578,0.000687,7.000000,7,0.015873,0.000073,0.000011,0.174702
20,micro,Profit Margin Expansion Better Than Expected,2,0.001903,0.000285,19.500000,39,0.031746,0.000060,0.000009,0.112627
21,micro,Profit Margin Contraction Worse Than Expected,1,-0.011991,0.001799,25.000000,25,0.015873,-0.000190,0.000029,0.282742
22,micro,Strategic Partnership Announcement,6,0.003712,0.000557,15.500000,93,0.095238,0.000354,0.000053,0.157312
23,micro,Product Innovation Launch,7,0.003140,0.000471,11.571429,81,0.111111,0.000349,0.000052,0.144676

### Merge the Factor Time Metrics to Update Each Factor Time

In [39]:
def merge_factor_time_data_with_llm(old_factor_time_df, new_factor_time_df, ticker, language="English"):
    """
    Merge old and new factor time data using LLM to map similar factors.
    
    Args:
        old_factor_time_df: Existing factor time DataFrame
        new_factor_time_df: New factor time DataFrame
        ticker: Stock ticker symbol
        language: Language for output
        
    Returns:
        Merged factor time DataFrame with combined time intervals
    """
    import json
    from LLM_Call_Agent import LLMCallAgent
    
    print("🔄 Merging factor time data using LLM mapping...")
    
    # Extract unique factors from both DataFrames
    old_factors = old_factor_time_df['factor_name'].unique().tolist()
    new_factors = new_factor_time_df['factor_name'].unique().tolist()
    
    print(f"📊 Old factors: {len(old_factors)}")
    print(f"📊 New factors: {len(new_factors)}")
    
    # Create LLM prompt for factor mapping
    prompt = f"""
You are a financial analyst expert. Analyze the old and new factor lists for {ticker} and create a mapping strategy.

OLD FACTORS:
{json.dumps(old_factors, indent=2)}

NEW FACTORS:
{json.dumps(new_factors, indent=2)}

TASK:
1. Map NEW factors to OLD factors where they represent the same underlying concept
2. Identify completely NEW factors that don't match any old factors
3. Create a mapping dictionary

RULES:
- Use semantic similarity (e.g., "Fed Rate Cut Expectation" matches "Fed Rate Cut Implementation")
- Consider expectation vs delivery variations as the same factor
- Keep the OLD factor name as the canonical name
- For new factors with no match, keep the new factor name

OUTPUT FORMAT:
{{
    "factor_mapping": {{
        "new_factor_name_1": "old_factor_name_1",
        "new_factor_name_2": "old_factor_name_2",
        "completely_new_factor": null
    }},
    "mapping_explanations": {{
        "new_factor_name_1": "Same concept as old factor, different expectation/delivery phase",
        "completely_new_factor": "New factor not present in old data"
    }}
}}

Respond with ONLY the JSON object.
"""

    # Call LLM for mapping
    llm_agent = LLMCallAgent(default_provider="deepseek", default_model="deepseek-chat")
    
    raw_response = llm_agent.call_deepseek(
        prompt=prompt,
        system_message="You are a financial data analyst. Respond with valid JSON only.",
        model="deepseek-chat",
        max_tokens=2000,
        temperature=0.1,
    )
    
    if not raw_response:
        raise ValueError("Empty LLM response")
    
    # Parse LLM response
    import re
    cleaned = raw_response.strip().strip("`")
    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start != -1 and end != -1:
        cleaned = cleaned[start : end + 1]
    
    try:
        mapping_result = json.loads(cleaned)
        factor_mapping = mapping_result.get("factor_mapping", {})
        mapping_explanations = mapping_result.get("mapping_explanations", {})
    except:
        print("⚠️ LLM response parsing failed, using simple matching")
        # Fallback: simple exact matching
        factor_mapping = {}
        for new_factor in new_factors:
            if new_factor in old_factors:
                factor_mapping[new_factor] = new_factor
            else:
                factor_mapping[new_factor] = None
    
    print(f"✅ Factor mapping completed")
    print(f"   Mapped factors: {len([k for k, v in factor_mapping.items() if v is not None])}")
    print(f"   New factors: {len([k for k, v in factor_mapping.items() if v is None])}")
    
    # Create merged DataFrame
    merged_data = []
    
    # Add all old factor time data (keep as-is)
    for _, row in old_factor_time_df.iterrows():
        merged_data.append({
            'factor_name': row['factor_name'],
            'scope': row['scope'],
            'start_date': row['start_date'],
            'end_date': row['end_date'],
            'time_interval': row['time_interval'],
            'duration_days': row['duration_days']
        })
    
    # Process new factor time data
    for _, row in new_factor_time_df.iterrows():
        new_factor_name = row['factor_name']
        mapped_old_factor = factor_mapping.get(new_factor_name)
        
        if mapped_old_factor is not None:
            # This factor maps to an existing old factor - use old factor name
            merged_data.append({
                'factor_name': mapped_old_factor,  # Use old factor name
                'scope': row['scope'],
                'start_date': row['start_date'],
                'end_date': row['end_date'],
                'time_interval': row['time_interval'],
                'duration_days': row['duration_days']
            })
            print(f"   🔄 Mapped '{new_factor_name}' → '{mapped_old_factor}'")
        else:
            # This is a completely new factor - keep new factor name
            merged_data.append({
                'factor_name': new_factor_name,
                'scope': row['scope'],
                'start_date': row['start_date'],
                'end_date': row['end_date'],
                'time_interval': row['time_interval'],
                'duration_days': row['duration_days']
            })
            print(f"   ➕ Added new factor: '{new_factor_name}'")
    
    # Create merged DataFrame
    merged_factor_time_df = pd.DataFrame(merged_data)
    
    # Sort by factor_name and start_date
    merged_factor_time_df = merged_factor_time_df.sort_values(['factor_name', 'start_date']).reset_index(drop=True)
    
    print(f"\n✅ Factor time data merged successfully!")
    print(f"   Total time intervals: {len(merged_factor_time_df)}")
    print(f"   Unique factors: {len(merged_factor_time_df['factor_name'].unique())}")
    
    # Show summary
    factor_counts = merged_factor_time_df['factor_name'].value_counts()
    print(f"\n📊 Factor time interval counts:")
    for factor, count in factor_counts.head(10).items():
        print(f"   {factor}: {count} intervals")
    
    return merged_factor_time_df, factor_mapping, mapping_explanations

In [40]:

merged_factor_time_df, factor_mapping, explanations = merge_factor_time_data_with_llm(
    old_factor_time_df=factor_time_df,
    new_factor_time_df=New_factor_time_df,
    ticker=ticker,
    language="English"
)

🔄 Merging factor time data using LLM mapping...
📊 Old factors: 24
📊 New factors: 14
✅ Factor mapping completed
   Mapped factors: 10
   New factors: 4
   🔄 Mapped 'Fed Rate Cut Expectation' → 'Fed Rate Cut Expectation'
   🔄 Mapped 'Fed Rate Cut Expectation' → 'Fed Rate Cut Expectation'
   🔄 Mapped 'Fed Rate Cut Implementation' → 'Fed Rate Cut Expectation'
   🔄 Mapped 'Fed No Rate Cut Worse Than Expected' → 'Fed Rate Cut Worse Than Expected'
   ➕ Added new factor: 'Bitcoin Record Highs Better Than Expected'
   🔄 Mapped 'USMCA Trade Deal Renegotiation Worse Than Expected' → 'Trump Tariff Implementation'
   ➕ Added new factor: 'PCE Inflation Data As Expected'
   ➕ Added new factor: 'AI Bubble Concerns Worse Than Expected'
   🔄 Mapped 'Unbranded Processing Growth Bottoming Better Than Expected' → 'Payment Volume Growth Better Than Expected'
   🔄 Mapped 'Branded Checkout TPV Growth As Expected' → 'Payment Volume Growth Better Than Expected'
   🔄 Mapped 'Venmo Revenue Growth Better Than Expected' → 'Revenue Growth Better Than Expected'
   🔄 Mapped 'Q2 Earnings Underperformance Worse Than Expected' → 'Earnings Miss Worse Than Expected'
   🔄 Mapped 'BNPL Volume Growth Better Than Expected' → 'Payment Volume Growth Better Than Expected'
   🔄 Mapped 'BNPL Volume Growth Better Than Expected' → 'Payment Volume Growth Better Than Expected'
   🔄 Mapped 'Google AI Partnership Implementation' → 'Strategic Partnership Announcement'
   🔄 Mapped 'Google AI Partnership Implementation' → 'Strategic Partnership Announcement'
   ➕ Added new factor: 'Analyst Downgrade Worse Than Expected'

✅ Factor time data merged successfully!
   Total time intervals: 80
   Unique factors: 28

📊 Factor time interval counts:
   Payment Volume Growth Better Than Expected: 8 intervals
   Strategic Partnership Announcement: 8 intervals
   Fed Rate Cut Expectation: 8 intervals
   Product Innovation Launch: 7 intervals
   Earnings Miss Worse Than Expected: 6 intervals
   Trump Tariff Implementation: 5 intervals
   Trump Tariff Relief: 4 intervals
   Earnings Beat Better Than Expected: 4 intervals
   Market Volatility Increase: 3 intervals
   Revenue Growth Worse Than Expected: 2 intervals

In [41]:
merged_factor_time_df

,factor_name,scope,start_date,end_date,time_interval,duration_days
0,AI Bubble Concerns Worse Than Expected,macro,2025-09-29,2025-10-01,2025-09-29 to 2025-10-01,2
1,Active Account Growth Better Than Expected,micro,2025-02-11,2025-02-18,2025-02-11 to 2025-02-18,7
2,Analyst Downgrade Worse Than Expected,micro,2025-08-13,2025-08-21,2025-08-13 to 2025-08-21,8
3,Bitcoin Record Highs Better Than Expected,macro,2025-08-11,2025-08-13,2025-08-11 to 2025-08-13,2
4,Bond Yields Rising,macro,2025-01-06,2025-01-10,2025-01-06 to 2025-01-10,4
...,...,...,...,...,...,...
75,Trump Tariff Relief,macro,2025-04-16,2025-05-14,2025-04-16 to 2025-05-14,28
76,Trump Tariff Relief,macro,2025-05-23,2025-06-12,2025-05-23 to 2025-06-12,20
77,Trump Tariff Relief,macro,2025-07-11,2025-07-28,2025-07-11 to 2025-07-28,17
78,Weak Jobs Report Worse Than Expected,macro,2024-10-28,2024-11-01,2024-10-28 to 2024-11-01,4
79,Weak Jobs Report Worse Than Expected,macro,2025-08-01,2025-08-11,2025-08-01 to 2025-08-11,10